#
#     Sorbonne University
#     Washington University in Saint Louis
#     University of Texas at Austin
#

####################################################
# Compilation of colvars library for Tinker-HP     #
#                                                  #
# Declare the library to create                    #
####################################################

noinst_LIBRARIES = libcolvars.a

AM_CXXFLAGS=$(LIB2DECOMP_INC) $(PLUMEDFLAG) $(LIBPLUMED_INC) $(LIBCOLVARS_INC) $(TCLFLAG) $(LIBTCL_INC)
#
# Declare her sources
#

libcolvars_a_SOURCES =
libcolvars_a_SOURCES += src/colvar.cpp
libcolvars_a_SOURCES += src/colvar_neuralnetworkcompute.cpp
libcolvars_a_SOURCES += src/colvaratoms.cpp
libcolvars_a_SOURCES += src/colvarbias.cpp
libcolvars_a_SOURCES += src/colvarbias_abf.cpp
libcolvars_a_SOURCES += src/colvarbias_abmd.cpp
libcolvars_a_SOURCES += src/colvarbias_alb.cpp
libcolvars_a_SOURCES += src/colvarbias_histogram.cpp
libcolvars_a_SOURCES += src/colvarbias_histogram_reweight_amd.cpp
libcolvars_a_SOURCES += src/colvarbias_meta.cpp
libcolvars_a_SOURCES += src/colvarbias_opes.cpp
libcolvars_a_SOURCES += src/colvarbias_restraint.cpp
libcolvars_a_SOURCES += src/colvarcomp.cpp
libcolvars_a_SOURCES += src/colvarcomp_alchlambda.cpp
libcolvars_a_SOURCES += src/colvarcomp_angles.cpp
libcolvars_a_SOURCES += src/colvarcomp_apath.cpp
libcolvars_a_SOURCES += src/colvarcomp_combination.cpp
libcolvars_a_SOURCES += src/colvarcomp_coordnums.cpp
libcolvars_a_SOURCES += src/colvarcomp_distances.cpp
libcolvars_a_SOURCES += src/colvarcomp_gpath.cpp
libcolvars_a_SOURCES += src/colvarcomp_neuralnetwork.cpp
libcolvars_a_SOURCES += src/colvarcomp_protein.cpp
libcolvars_a_SOURCES += src/colvarcomp_rotations.cpp
libcolvars_a_SOURCES += src/colvarcomp_torchann.cpp
libcolvars_a_SOURCES += src/colvarcomp_volmaps.cpp
libcolvars_a_SOURCES += src/colvardeps.cpp
libcolvars_a_SOURCES += src/colvargrid.cpp
libcolvars_a_SOURCES += src/colvargrid_integrate.cpp
libcolvars_a_SOURCES += src/colvarmodule.cpp
libcolvars_a_SOURCES += src/colvarparams.cpp
libcolvars_a_SOURCES += src/colvarparse.cpp
libcolvars_a_SOURCES += src/colvarproxy.cpp
libcolvars_a_SOURCES += src/colvarproxy_io.cpp
libcolvars_a_SOURCES += src/colvarproxy_replicas.cpp
libcolvars_a_SOURCES += src/colvarproxy_system.cpp
libcolvars_a_SOURCES += src/colvarproxy_tcl.cpp
libcolvars_a_SOURCES += src/colvarproxy_volmaps.cpp
libcolvars_a_SOURCES += src/colvars_memstream.cpp
libcolvars_a_SOURCES += src/colvarscript.cpp
libcolvars_a_SOURCES += src/colvarscript_commands.cpp
libcolvars_a_SOURCES += src/colvarscript_commands_bias.cpp
libcolvars_a_SOURCES += src/colvarscript_commands_colvar.cpp
libcolvars_a_SOURCES += src/colvartypes.cpp
libcolvars_a_SOURCES += src/colvarvalue.cpp
libcolvars_a_SOURCES += src/nr_jacobi.cpp
#
#
# End of Makefile.am
#
