#
# 
#     Sorbonne University
#     Washington University in Saint Louis
#     University of Texas at Austin
# 

# 
# Compilation of Programs Tinker-HP's programs
# 

#
# Declare all the programs
#

bin_PROGRAMS =
bin_PROGRAMS += analyze
bin_PROGRAMS += bar
bin_PROGRAMS += dynamic
bin_PROGRAMS += minimize
bin_PROGRAMS += pimd
bin_PROGRAMS += testgrad

#############################################
#
# Add your New main Here
#
# bin_PROGRAMMS +=  yourmain
#
#############################################

#
# Declare their sources and the dependencies
#

analyze_SOURCES       = analyze.f90
analyze_DEPENDENCIES  = libtinkermod.a libtinkercalc.a libtinkerclv.a @COLVARSDEP@ @PLUMEDDEP@

bar_SOURCES           = bar.f90
bar_DEPENDENCIES      = libtinkermod.a libtinkercalc.a libtinkerclv.a @COLVARSDEP@ @PLUMEDDEP@

dynamic_SOURCES       = dynamic.f90
dynamic_DEPENDENCIES  = libtinkermod.a libtinkercalc.a libtinkerclv.a @COLVARSDEP@ @PLUMEDDEP@

minimize_SOURCES      = minimize.f90
minimize_DEPENDENCIES = libtinkermod.a libtinkercalc.a libtinkerclv.a @COLVARSDEP@ @PLUMEDDEP@

pimd_SOURCES      = pimd.f90
pimd_DEPENDENCIES = libtinkermod.a libtinkercalc.a libtinkerclv.a @COLVARSDEP@ @PLUMEDDEP@

testgrad_SOURCES      = testgrad.f90
testgrad_DEPENDENCIES = libtinkermod.a libtinkercalc.a libtinkerclv.a @COLVARSDEP@ @PLUMEDDEP@

#############################################
#
# Add the sources of your new main Here
#
# yourmain_SOURCES      = yourmain.f90
# yourmain_DEPENDENCIES = libtinkermod.a libtinkercalc.a
#
#############################################

#
# Declare the libraries they need
# 

#
# These libraries come from tinker 
#

LDADD  = libtinkercalc.a libtinkermod.a libtinkerclv.a

#
# These libraries are external and defined by configure
#

LDADD += $(LIBCOLVARS_LIB) $(LIBTCL_LIB) $(LIBPLUMED_LIB) $(LIB2DECOMP_LIB) $(FFTW_LIBS) $(BLAS) @NVMPICXX@

#
# Declare the Tinker libraries needed by the programs
#
# libtinkermod.a contains all the modules
# libtinkercal.a contains all the calculation routines
#

noinst_LIBRARIES = libtinkermod.a libtinkercalc.a libtinkerclv.a

#
# states that libtinkercal.a depends upon libtinkermod.a
#
#
libtinkercalc_a_DEPENDENCIES = libtinkermod.a libtinkerclv.a

#
# Declare that depend.mk and plumedlibs should be generated before everything else
#

BUILT_SOURCES  = depend.mk
BUILT_SOURCES += plumed
BUILT_SOURCES += colvars
BUILT_SOURCES += tcl

#
#depend.mk is ghenerated by a python script
depend.mk: 
	-$(PYTHON) ./Tinker_deps.py *.f90 > $@
#
# plumedlibs are generated, either by plumed.mk or noplumed.mk
plumed.mk:
	-echo "plumed:" > $@
	-echo "		-(cd ../plumed2 ; make -j 32 install VERBOSE=1)" >> $@
	-cp ../plumed2/MakeInstall.mk ../plumed2/install.mk
noplumed.mk:
	-echo "plumed:" > $@
	-echo "		-touch plumed" >> $@
	-echo "install:" > ../plumed2/install.mk
	-echo "		-touch noplumed" >> ../plumed2/install.mk
	-echo "all:" >> ../plumed2/install.mk
	-echo "		-touch noplumed" >> ../plumed2/install.mk
	-echo "clean:" >> ../plumed2/install.mk
	-echo "		-rm -f noplumed" >> ../plumed2/install.mk
#
# colvarslib is generated, either by colvars.mk or nocolvars.mk

colvars.mk:
	-echo "colvars:" > $@
	-echo "		-(cd ../colvars ; make -j 8 VERBOSE=1)" >> $@
nocolvars.mk:
	-echo "colvars:" > $@
	-echo "		-touch colvars" >> $@
# We remove the Makefile generated by configure
	-echo "		-/bin/rm -f ../colvars/Makefile" >> $@
# and generate a dumb Makefile, whitch does nothing, but answers the main requests (all, install, clean)
	-echo "		-echo \"all:\" > ../colvars/Makefile" >> $@
	-echo "		-echo \"	-touch colvars\" >> ../colvars/Makefile" >> $@
	-echo "		-echo \"install:\" >> ../colvars/Makefile" >> $@
	-echo "		-echo \"	-touch colvars\" >> ../colvars/Makefile" >> $@
	-echo "		-echo \"clean:\" >> ../colvars/Makefile" >> $@
	-echo "		-echo \"	-rm -f *.o libcolvars.a colvars\" >> ../colvars/Makefile" >> $@

#
# tcllib is generated, either by tcl.mk or notcl.mk

tcl.mk:
	-echo "tcl:" > $@
	-echo "		-(cd ../tcl8.6.13/unix ; make -j 8 VERBOSE=1)" >> $@
notcl.mk:
	-echo "tcl:" > $@
	-echo "		-touch tcl" >> $@
# We remove the Makefile generated by configure
	-echo "		-/bin/rm -f ../tcl8.6.13/unix/Makefile" >> $@
# and generate a dumb Makefile, whitch does nothing, but answers the main requests (all, install, clean)
	-echo "		-echo \"all:\" > ../tcl8.6.13/unix/Makefile" >> $@
	-echo "		-echo \"	-touch tcl\" >> ../tcl8.6.13/unix/Makefile" >> $@
	-echo "		-echo \"install:\" >> ../tcl8.6.13/unix/Makefile" >> $@
	-echo "		-echo \"	-touch tcl\" >> ../tcl8.6.13/unix/Makefile" >> $@
	-echo "		-echo \"clean:\" >> ../tcl8.6.13/unix/Makefile" >> $@
	-echo "		-echo \"	-rm -f *.o libtcl* tcl\" >> ../tcl8.6.13/unix/Makefile" >> $@

#
# Declare the sources for the modules. They are compiled in the order determined by depend.mk
#
libtinkermod_a_SOURCES = 
libtinkermod_a_SOURCES += MOD_sizes.f90
libtinkermod_a_SOURCES += MOD_action.f90
libtinkermod_a_SOURCES += MOD_analyz.f90
libtinkermod_a_SOURCES += MOD_angang.f90
libtinkermod_a_SOURCES += MOD_angle.f90
libtinkermod_a_SOURCES += MOD_angpot.f90
libtinkermod_a_SOURCES += MOD_angtor.f90
libtinkermod_a_SOURCES += MOD_argue.f90
libtinkermod_a_SOURCES += MOD_ascii.f90
libtinkermod_a_SOURCES += MOD_atmlst.f90
libtinkermod_a_SOURCES += MOD_atmtyp.f90
libtinkermod_a_SOURCES += MOD_atoms.f90
libtinkermod_a_SOURCES += MOD_bath.f90
libtinkermod_a_SOURCES += MOD_beads.f90
libtinkermod_a_SOURCES += MOD_bitor.f90
libtinkermod_a_SOURCES += MOD_bndpot.f90
libtinkermod_a_SOURCES += MOD_bond.f90
libtinkermod_a_SOURCES += MOD_bound.f90
libtinkermod_a_SOURCES += MOD_boxes.f90
libtinkermod_a_SOURCES += MOD_cell.f90
libtinkermod_a_SOURCES += MOD_colvars.f90
libtinkermod_a_SOURCES += MOD_cflux.f90
libtinkermod_a_SOURCES += MOD_charge.f90
libtinkermod_a_SOURCES += MOD_chgpen.f90
libtinkermod_a_SOURCES += MOD_chgpot.f90
libtinkermod_a_SOURCES += MOD_chgtrn.f90
libtinkermod_a_SOURCES += MOD_chunks.f90
libtinkermod_a_SOURCES += MOD_couple.f90
libtinkermod_a_SOURCES += MOD_ctrpot.f90
libtinkermod_a_SOURCES += MOD_cutoff.f90
libtinkermod_a_SOURCES += MOD_dcdmod.f90
libtinkermod_a_SOURCES += MOD_deconvolution.f90
libtinkermod_a_SOURCES += MOD_deriv.f90
libtinkermod_a_SOURCES += MOD_divcon.f90
libtinkermod_a_SOURCES += MOD_disp.f90
libtinkermod_a_SOURCES += MOD_domdec.f90
libtinkermod_a_SOURCES += MOD_dsppot.f90
libtinkermod_a_SOURCES += MOD_energi.f90
libtinkermod_a_SOURCES += MOD_ewald.f90
libtinkermod_a_SOURCES += MOD_fft.f90
libtinkermod_a_SOURCES += MOD_fields.f90
libtinkermod_a_SOURCES += MOD_files.f90
libtinkermod_a_SOURCES += MOD_freeze.f90
libtinkermod_a_SOURCES += MOD_group.f90
libtinkermod_a_SOURCES += MOD_improp.f90
libtinkermod_a_SOURCES += MOD_imptor.f90
libtinkermod_a_SOURCES += MOD_inform.f90
libtinkermod_a_SOURCES += MOD_inter.f90
libtinkermod_a_SOURCES += MOD_iounit.f90
libtinkermod_a_SOURCES += MOD_kanang.f90
libtinkermod_a_SOURCES += MOD_kangs.f90
libtinkermod_a_SOURCES += MOD_kantor.f90
libtinkermod_a_SOURCES += MOD_katoms.f90
libtinkermod_a_SOURCES += MOD_kbonds.f90
libtinkermod_a_SOURCES += MOD_kcflux.f90
libtinkermod_a_SOURCES += MOD_kchrge.f90
libtinkermod_a_SOURCES += MOD_kcpen.f90
libtinkermod_a_SOURCES += MOD_kctrn.f90
libtinkermod_a_SOURCES += MOD_kdsp.f90
libtinkermod_a_SOURCES += MOD_keys.f90
libtinkermod_a_SOURCES += MOD_kgeoms.f90
libtinkermod_a_SOURCES += MOD_khbond.f90
libtinkermod_a_SOURCES += MOD_kiprop.f90
libtinkermod_a_SOURCES += MOD_kitors.f90
libtinkermod_a_SOURCES += MOD_kmulti.f90
libtinkermod_a_SOURCES += MOD_kopbnd.f90
libtinkermod_a_SOURCES += MOD_kopdst.f90
libtinkermod_a_SOURCES += MOD_kpitor.f90
libtinkermod_a_SOURCES += MOD_kpolpr.f90
libtinkermod_a_SOURCES += MOD_kpolr.f90
libtinkermod_a_SOURCES += MOD_krepl.f90
libtinkermod_a_SOURCES += MOD_kstbnd.f90
libtinkermod_a_SOURCES += MOD_ksttor.f90
libtinkermod_a_SOURCES += MOD_ktorsn.f90
libtinkermod_a_SOURCES += MOD_ktrtor.f90
libtinkermod_a_SOURCES += MOD_kurybr.f90
libtinkermod_a_SOURCES += MOD_kvdwpr.f90
libtinkermod_a_SOURCES += MOD_kvdws.f90
libtinkermod_a_SOURCES += MOD_langevin.f90
libtinkermod_a_SOURCES += MOD_linmin.f90
libtinkermod_a_SOURCES += MOD_math.f90
libtinkermod_a_SOURCES += MOD_mdstuf.f90
libtinkermod_a_SOURCES += MOD_mdstuf1.f90
libtinkermod_a_SOURCES += MOD_merck.f90
libtinkermod_a_SOURCES += MOD_minima.f90
libtinkermod_a_SOURCES += MOD_molcul.f90
libtinkermod_a_SOURCES += MOD_moldyn.f90
libtinkermod_a_SOURCES += MOD_commstuffpi.f90
libtinkermod_a_SOURCES += MOD_mplpot.f90
libtinkermod_a_SOURCES += MOD_mpole.f90
libtinkermod_a_SOURCES += MOD_msmd.f90
libtinkermod_a_SOURCES += MOD_mutant.f90
libtinkermod_a_SOURCES += MOD_neigh.f90
libtinkermod_a_SOURCES += MOD_opbend.f90
libtinkermod_a_SOURCES += MOD_opdist.f90
libtinkermod_a_SOURCES += MOD_output.f90
libtinkermod_a_SOURCES += MOD_params.f90
libtinkermod_a_SOURCES += MOD_pitors.f90
libtinkermod_a_SOURCES += MOD_plumed.f90
libtinkermod_a_SOURCES += MOD_pme.f90
libtinkermod_a_SOURCES += MOD_polar.f90
libtinkermod_a_SOURCES += MOD_polgrp.f90
libtinkermod_a_SOURCES += MOD_polpot.f90
libtinkermod_a_SOURCES += MOD_potent.f90
libtinkermod_a_SOURCES += MOD_precis.f90
libtinkermod_a_SOURCES += MOD_ptable.f90
libtinkermod_a_SOURCES += MOD_qtb.f90
libtinkermod_a_SOURCES += MOD_repel.f90
libtinkermod_a_SOURCES += MOD_replicas.f90
libtinkermod_a_SOURCES += MOD_reppot.f90
libtinkermod_a_SOURCES += MOD_resdue.f90
libtinkermod_a_SOURCES += MOD_ring.f90
libtinkermod_a_SOURCES += MOD_scales.f90
libtinkermod_a_SOURCES += MOD_shunt.f90
libtinkermod_a_SOURCES += MOD_spectra.f90
libtinkermod_a_SOURCES += MOD_strbnd.f90
libtinkermod_a_SOURCES += MOD_strtor.f90
libtinkermod_a_SOURCES += MOD_subInform.f90
libtinkermod_a_SOURCES += MOD_timestat.f90
libtinkermod_a_SOURCES += MOD_titles.f90
libtinkermod_a_SOURCES += MOD_torpot.f90
libtinkermod_a_SOURCES += MOD_tors.f90
libtinkermod_a_SOURCES += MOD_tortor.f90
libtinkermod_a_SOURCES += MOD_units.f90
libtinkermod_a_SOURCES += MOD_uprior.f90
libtinkermod_a_SOURCES += MOD_urey.f90
libtinkermod_a_SOURCES += MOD_urypot.f90
libtinkermod_a_SOURCES += MOD_usage.f90
libtinkermod_a_SOURCES += MOD_utilbaoab.f90
libtinkermod_a_SOURCES += MOD_utilbaoabpi.f90
libtinkermod_a_SOURCES += MOD_vdw.f90
libtinkermod_a_SOURCES += MOD_vdwpot.f90
libtinkermod_a_SOURCES += MOD_virial.f90

#
# Declare the sources for the colvar interface routines
#
libtinkerclv_a_SOURCES =
libtinkerclv_a_SOURCES += colvarproxy_tinkerhp.cpp
libtinkerclv_a_SOURCES += colvarproxy_tinkerhp.h
libtinkerclv_a_SOURCES += colvarproxy_tinkerhp_interface.h
libtinkerclv_a_CXXFLAGS = @LIBCOLVARS_INC@ @LIBTCL_INC@

#############################################
#
# Add your new routines here
#
# libtinkermod_a_SOURCES += MOD_xxxx.f90
#
#############################################

#
# Declare the sources for the calculation routines
#
 
libtinkercalc_a_SOURCES =
libtinkercalc_a_SOURCES += active.f90
libtinkercalc_a_SOURCES += alterchg.f90
libtinkercalc_a_SOURCES += analysis.f90
libtinkercalc_a_SOURCES += angles.f90
libtinkercalc_a_SOURCES += attach.f90
libtinkercalc_a_SOURCES += baoab.f90
libtinkercalc_a_SOURCES += baoabrespa.f90
libtinkercalc_a_SOURCES += baoabrespa1.f90
libtinkercalc_a_SOURCES += baoabpi.f90
libtinkercalc_a_SOURCES += baoabrespapi.f90
libtinkercalc_a_SOURCES += basefile.f90
libtinkercalc_a_SOURCES += beeman.f90
libtinkercalc_a_SOURCES += bicubic.f90
libtinkercalc_a_SOURCES += bitors.f90
libtinkercalc_a_SOURCES += bonds.f90
libtinkercalc_a_SOURCES += bounds.f90
libtinkercalc_a_SOURCES += boundspi.f90
libtinkercalc_a_SOURCES += calendar.f90
libtinkercalc_a_SOURCES += chkpole.f90
libtinkercalc_a_SOURCES += chkring.f90
libtinkercalc_a_SOURCES += chkxyz.f90
libtinkercalc_a_SOURCES += cholesky.f90
libtinkercalc_a_SOURCES += cluster.f90
libtinkercalc_a_SOURCES += command.f90
libtinkercalc_a_SOURCES += control.f90
libtinkercalc_a_SOURCES += cspline.f90
libtinkercalc_a_SOURCES += cutoffs.f90
libtinkercalc_a_SOURCES += damping.f90
libtinkercalc_a_SOURCES += dcdio.f90
libtinkercalc_a_SOURCES += dcinduce_pme.f90
libtinkercalc_a_SOURCES += dcinduce_pme2.f90
libtinkercalc_a_SOURCES += dcinduce_shortreal.f90
libtinkercalc_a_SOURCES += dcflux.f90
libtinkercalc_a_SOURCES += diis.f90
libtinkercalc_a_SOURCES += domdecstuff.f90
libtinkercalc_a_SOURCES += eangang.f90
libtinkercalc_a_SOURCES += eangang1.f90
libtinkercalc_a_SOURCES += eangang3.f90
libtinkercalc_a_SOURCES += eangle.f90
libtinkercalc_a_SOURCES += eangle1.f90
libtinkercalc_a_SOURCES += eangle3.f90
libtinkercalc_a_SOURCES += eangtor.f90
libtinkercalc_a_SOURCES += eangtor1.f90
libtinkercalc_a_SOURCES += eangtor3.f90
libtinkercalc_a_SOURCES += ebond.f90
libtinkercalc_a_SOURCES += ebond1.f90
libtinkercalc_a_SOURCES += ebond3.f90
libtinkercalc_a_SOURCES += echarge.f90
libtinkercalc_a_SOURCES += echarge1.f90
libtinkercalc_a_SOURCES += echarge3.f90
libtinkercalc_a_SOURCES += echgtrn.f90
libtinkercalc_a_SOURCES += echgtrn1.f90
libtinkercalc_a_SOURCES += echgtrn3.f90
libtinkercalc_a_SOURCES += edisp.f90
libtinkercalc_a_SOURCES += edisp1.f90
libtinkercalc_a_SOURCES += edisp3.f90
libtinkercalc_a_SOURCES += egeom.f90
libtinkercalc_a_SOURCES += egeom1.f90
libtinkercalc_a_SOURCES += egeom3.f90
libtinkercalc_a_SOURCES += ehal.f90
libtinkercalc_a_SOURCES += ehal1.f90
libtinkercalc_a_SOURCES += ehal3.f90
libtinkercalc_a_SOURCES += eimprop.f90
libtinkercalc_a_SOURCES += eimprop1.f90
libtinkercalc_a_SOURCES += eimprop3.f90
libtinkercalc_a_SOURCES += eimptor.f90
libtinkercalc_a_SOURCES += eimptor1.f90
libtinkercalc_a_SOURCES += eimptor3.f90
libtinkercalc_a_SOURCES += elj.f90
libtinkercalc_a_SOURCES += elj1.f90
libtinkercalc_a_SOURCES += elj3.f90
libtinkercalc_a_SOURCES += empole.f90
libtinkercalc_a_SOURCES += empole0.f90
libtinkercalc_a_SOURCES += empole1.f90
libtinkercalc_a_SOURCES += empole3.f90
libtinkercalc_a_SOURCES += energy.f90
libtinkercalc_a_SOURCES += eopbend.f90
libtinkercalc_a_SOURCES += eopbend1.f90
libtinkercalc_a_SOURCES += eopbend3.f90
libtinkercalc_a_SOURCES += eopdist.f90
libtinkercalc_a_SOURCES += eopdist1.f90
libtinkercalc_a_SOURCES += eopdist3.f90
libtinkercalc_a_SOURCES += epitors.f90
libtinkercalc_a_SOURCES += epitors1.f90
libtinkercalc_a_SOURCES += epitors3.f90
libtinkercalc_a_SOURCES += epolar.f90
libtinkercalc_a_SOURCES += epolar1.f90
libtinkercalc_a_SOURCES += epolar1_group.f90
libtinkercalc_a_SOURCES += epolar1tcg.f90
libtinkercalc_a_SOURCES += epolar1tcg1shortreal.f90
libtinkercalc_a_SOURCES += epolar1tcg2.f90
libtinkercalc_a_SOURCES += epolar1tcg2_2.f90
libtinkercalc_a_SOURCES += epolar1tcg2shortreal.f90
libtinkercalc_a_SOURCES += epolar1tcg_2.f90
libtinkercalc_a_SOURCES += epolar3.f90
libtinkercalc_a_SOURCES += epolar3_group.f90
libtinkercalc_a_SOURCES += epolar3tcg.f90
libtinkercalc_a_SOURCES += epolar3tcg_2.f90
libtinkercalc_a_SOURCES += erepel.f90
libtinkercalc_a_SOURCES += erepel1.f90
libtinkercalc_a_SOURCES += erepel3.f90
libtinkercalc_a_SOURCES += erf.f90
libtinkercalc_a_SOURCES += esmd1.f90
libtinkercalc_a_SOURCES += estrbnd.f90
libtinkercalc_a_SOURCES += estrbnd1.f90
libtinkercalc_a_SOURCES += estrbnd3.f90
libtinkercalc_a_SOURCES += estrtor.f90
libtinkercalc_a_SOURCES += estrtor1.f90
libtinkercalc_a_SOURCES += estrtor3.f90
libtinkercalc_a_SOURCES += etors.f90
libtinkercalc_a_SOURCES += etors1.f90
libtinkercalc_a_SOURCES += etors3.f90
libtinkercalc_a_SOURCES += etortor.f90
libtinkercalc_a_SOURCES += etortor1.f90
libtinkercalc_a_SOURCES += etortor3.f90
libtinkercalc_a_SOURCES += eurey.f90
libtinkercalc_a_SOURCES += eurey1.f90
libtinkercalc_a_SOURCES += eurey3.f90
libtinkercalc_a_SOURCES += evcorr.f90
libtinkercalc_a_SOURCES += extra.f90
libtinkercalc_a_SOURCES += extra1.f90
libtinkercalc_a_SOURCES += extra3.f90
libtinkercalc_a_SOURCES += fatal.f90
libtinkercalc_a_SOURCES += fft_mpi.f90
libtinkercalc_a_SOURCES += field.f90
libtinkercalc_a_SOURCES += final.f90
libtinkercalc_a_SOURCES += freeunit.f90
libtinkercalc_a_SOURCES += geometry.f90
libtinkercalc_a_SOURCES += getkey.f90
libtinkercalc_a_SOURCES += getnumb.f90
libtinkercalc_a_SOURCES += getprm.f90
libtinkercalc_a_SOURCES += getstring.f90
libtinkercalc_a_SOURCES += gettext.f90
libtinkercalc_a_SOURCES += getword.f90
libtinkercalc_a_SOURCES += getxyz.f90
libtinkercalc_a_SOURCES += gradient.f90
libtinkercalc_a_SOURCES += groups.f90
libtinkercalc_a_SOURCES += image.f90
libtinkercalc_a_SOURCES += initatom.f90
libtinkercalc_a_SOURCES += initial.f90
libtinkercalc_a_SOURCES += initprm.f90
libtinkercalc_a_SOURCES += initres.f90
libtinkercalc_a_SOURCES += invert.f90
libtinkercalc_a_SOURCES += kangang.f90
libtinkercalc_a_SOURCES += kangle.f90
libtinkercalc_a_SOURCES += kangtor.f90
libtinkercalc_a_SOURCES += katom.f90
libtinkercalc_a_SOURCES += kbond.f90
libtinkercalc_a_SOURCES += kcharge.f90
libtinkercalc_a_SOURCES += kchgflx.f90
libtinkercalc_a_SOURCES += kchgtrn.f90
libtinkercalc_a_SOURCES += kdisp.f90
libtinkercalc_a_SOURCES += kewald.f90
libtinkercalc_a_SOURCES += kgeom.f90
libtinkercalc_a_SOURCES += kimprop.f90
libtinkercalc_a_SOURCES += kimptor.f90
libtinkercalc_a_SOURCES += kinetic.f90
libtinkercalc_a_SOURCES += kmpole.f90
libtinkercalc_a_SOURCES += kopbend.f90
libtinkercalc_a_SOURCES += kopdist.f90
libtinkercalc_a_SOURCES += kpitors.f90
libtinkercalc_a_SOURCES += kpolar.f90
libtinkercalc_a_SOURCES += krepel.f90
libtinkercalc_a_SOURCES += ksmd.f90
libtinkercalc_a_SOURCES += kstrbnd.f90
libtinkercalc_a_SOURCES += kstrtor.f90
libtinkercalc_a_SOURCES += ktors.f90
libtinkercalc_a_SOURCES += ktortor.f90
libtinkercalc_a_SOURCES += kurey.f90
libtinkercalc_a_SOURCES += kvdw.f90
libtinkercalc_a_SOURCES += lattice.f90
libtinkercalc_a_SOURCES += lbfgs.f90
libtinkercalc_a_SOURCES += linalg.f90
libtinkercalc_a_SOURCES += maxwell.f90
libtinkercalc_a_SOURCES += mdinit.f90
libtinkercalc_a_SOURCES += mdinitbead.f90
libtinkercalc_a_SOURCES += mdinitreps.f90
libtinkercalc_a_SOURCES += mdrest.f90
libtinkercalc_a_SOURCES += mdsave.f90
libtinkercalc_a_SOURCES += mdsavebeads.f90
libtinkercalc_a_SOURCES += mdstat.f90
libtinkercalc_a_SOURCES += mdstatpi.f90
libtinkercalc_a_SOURCES += mechanic.f90
libtinkercalc_a_SOURCES += molecule.f90
libtinkercalc_a_SOURCES += mpistuff.f90
libtinkercalc_a_SOURCES += mutate.f90
libtinkercalc_a_SOURCES += nblist.f90
libtinkercalc_a_SOURCES += newinduce_group.f90
libtinkercalc_a_SOURCES += newinduce_pme.f90
libtinkercalc_a_SOURCES += newinduce_pme2.f90
libtinkercalc_a_SOURCES += newinduce_shortreal.f90
libtinkercalc_a_SOURCES += nextarg.f90
libtinkercalc_a_SOURCES += nexttext.f90
libtinkercalc_a_SOURCES += nspline.f90
libtinkercalc_a_SOURCES += number.f90
libtinkercalc_a_SOURCES += numeral.f90
libtinkercalc_a_SOURCES += openend.f90
libtinkercalc_a_SOURCES += optsave.f90
libtinkercalc_a_SOURCES += pmestuff.f90
libtinkercalc_a_SOURCES += precise.f90
libtinkercalc_a_SOURCES += pressure.f90
libtinkercalc_a_SOURCES += prime.f90
libtinkercalc_a_SOURCES += prmkey.f90
libtinkercalc_a_SOURCES += promo.f90
libtinkercalc_a_SOURCES += promosmd.f90
libtinkercalc_a_SOURCES += prtdyn.f90
libtinkercalc_a_SOURCES += prtdynbeads.f90
libtinkercalc_a_SOURCES += prtxyz.f90
libtinkercalc_a_SOURCES += random.f90
libtinkercalc_a_SOURCES += rattle.f90
libtinkercalc_a_SOURCES += readdyn.f90
libtinkercalc_a_SOURCES += readprm.f90
libtinkercalc_a_SOURCES += readxyz.f90
libtinkercalc_a_SOURCES += respa.f90
libtinkercalc_a_SOURCES += respa1.f90
libtinkercalc_a_SOURCES += rings.f90
libtinkercalc_a_SOURCES += rotpole.f90
libtinkercalc_a_SOURCES += scalders.f90
libtinkercalc_a_SOURCES += search.f90
libtinkercalc_a_SOURCES += shakeup.f90
libtinkercalc_a_SOURCES += sort.f90
libtinkercalc_a_SOURCES += suffix.f90
libtinkercalc_a_SOURCES += switch.f90
libtinkercalc_a_SOURCES += switch_group.f90
libtinkercalc_a_SOURCES += tcgstuff.f90
libtinkercalc_a_SOURCES += temper.f90
libtinkercalc_a_SOURCES += torphase.f90
libtinkercalc_a_SOURCES += torque.f90
libtinkercalc_a_SOURCES += torsions.f90
libtinkercalc_a_SOURCES += trimtext.f90
libtinkercalc_a_SOURCES += unitcell.f90
libtinkercalc_a_SOURCES += verlet.f90
libtinkercalc_a_SOURCES += version.f90

#############################################
#
# Add your new routines here
#
# libtinkercalc_a_SOURCES += yourexplicitname.f90
#
#############################################

#
#FLAGS to use for the compilation of all sources
#
 
#
# LIB2DECOMP_INC is only used when compiling fft_mpi.f90
# So, this include flag is used only for *.f90 sources
# For *.f90 sources, that would have been AM_FFLAGS
#
AM_FCFLAGS=$(LIB2DECOMP_INC) $(PLUMEDFLAG) $(LIBPLUMED_INC) $(LIBCOLVARS_INC) $(TCLFLAG) $(LIBTCL_INC)
 
#
# local cleaning of *.mod files
#


clean-local :
	-rm -f *.mod depend.mk plumed.mk noplumed.mk plumed colvars.mk nocolvars.mk colvars tcl.mk notcl.mk tcl *_genmod.f90 *.debug

#
# include dependencies (Key substituted by configure)
# It should not be an explicit "include depend.mk"
# because depend.mk is created AFTER automake has done its job
#
@INCLUDE_DEPEND_MK@
#
# include plumed generation (Key substituted by configure)
# So, it's either plumed.mk or noplumed.mk
#
@INCLUDE_PLUMED_MK@
#
# include colvars generation (Key substituted by configure)
# So, it's either colvars.mk or nocolvars.mk
#
@INCLUDE_COLVARS_MK@
#
# include tcl generation (Key substituted by configure)
# So, it's either tcl.mk or notcl.mk
#
@INCLUDE_TCL_MK@
#
# End of Makefile.am
#
