extern int32_t init_ml_ressources(
    int32_t rank,
    int32_t devID,
    char *model_file,
    int32_t debug,
    int32_t port,
    int32_t use_lambda,
    float qtot,
    float qligand,
    int32_t gc_stride,
    int32_t nat,
    int32_t *species,
    int32_t nligand,
    int32_t *index_ligand);

extern int32_t ml_models(
    uint64_t coord,
    uint64_t energy,
    uint64_t gradient,
    uint64_t vir,
    float *cell,
    uint64_t species,
    uint64_t l1,
    uint64_t l2,
    uint64_t dist,
    uint64_t dv,
    uint64_t trueat,
    int32_t natm,
    int32_t npairs,
    int32_t natm_full,
    int32_t dograd,
    int32_t use_lambda,
    float elambda,
    float vlambda,
    uint64_t alch_group,
    uint64_t dedle,
    uint64_t dedlv);
